-- =================================================================================================
-- SCRIPT DE DATOS - GÉNEROS MUSICALES (150+)
-- =================================================================================================

INSERT INTO music_genres (name, description) VALUES
-- ROCK & METAL
('Rock', 'A broad genre of popular music that originated as "rock and roll" in the United States in the late 1940s and early 1950s.'),
('Hard Rock', 'A loosely defined subgenre of rock music that began in the mid-1960s, with the garage, psychedelic and blues rock movements.'),
('Heavy Metal', 'A genre of rock music that developed in the late 1960s and early 1970s, largely in the United Kingdom and the United States.'),
('Alternative Rock', 'A style of rock music that emerged from the independent music underground of the 1980s and became widely popular in the 1990s.'),
('Punk Rock', 'A rock music genre that developed in the mid-1970s in the United States, United Kingdom, and Australia.'),
('Grunge', 'An alternative rock genre and subculture that emerged during the mid-1980s in the American Pacific Northwest state of Washington.'),
('Progressive Rock', 'A broad genre of rock music that developed in the United Kingdom and United States throughout the mid-to-late 1960s.'),
('Indie Rock', 'A genre of rock music that originated in the United States and United Kingdom in the 1970s.'),
('Psychedelic Rock', 'A diverse style of rock music inspired, influenced, or representative of psychedelic culture.'),
('Glam Rock', 'A style of rock music that developed in the United Kingdom in the early 1970s performed by musicians who wore outrageous costumes, makeup, and hairstyles.'),
('Thrash Metal', 'An extreme subgenre of heavy metal music characterized by its overall aggression and often fast tempo.'),
('Death Metal', 'An extreme subgenre of heavy metal music. It typically employs heavily distorted and low-tuned guitars, played with techniques such as palm muting and tremolo picking.'),
('Black Metal', 'An extreme subgenre of heavy metal music. Common traits include fast tempos, a shrieking vocal style, heavily distorted guitars played with tremolo picking, raw recording, and unconventional song structures.'),
('Power Metal', 'A subgenre of heavy metal combining characteristics of traditional metal with speed metal, often within symphonic context.'),
('Nu Metal', 'A subgenre of alternative metal that combines elements of heavy metal music with elements of other genres such as hip hop, alternative rock, funk, industrial, and grunge.'),
('Metalcore', 'A fusion genre combining elements of extreme metal and hardcore punk.'),
('Symphonic Metal', 'A subgenre of heavy metal music that combines the heavy drums and guitars of metal with different elements of orchestral classical music.'),
('Folk Metal', 'A fusion genre of heavy metal music and traditional folk music that developed in Europe during the 1990s.'),
('Gothic Metal', 'A fusion genre that combines the heaviness of doom metal with the dark atmospheres of gothic rock.'),
('Industrial Metal', 'A musical genre that draws from industrial dance music, thrash metal and hardcore punk, using repeating metal guitar riffs, sampling, synthesizer or sequencer lines, and distorted vocals.'),
('Doom Metal', 'An extreme subgenre of heavy metal music that typically uses slower tempos, low-tuned guitars and a much "thicker" or "heavier" sound than other heavy metal genres.'),
('Stoner Rock', 'A fusion genre of rock music that combines elements of heavy metal and/or doom metal with psychedelic rock and acid rock.'),
('Post-Rock', 'A form of experimental rock characterized by a focus on exploring textures and timbre over traditional rock song structures, chords, or riffs.'),
('Shoegaze', 'A subgenre of indie and alternative rock characterized by its ethereal mixture of obscured vocals, guitar distortion and effects, feedback, and overwhelming volume.'),
('New Wave', 'A broad music genre that encompasses numerous pop-oriented styles from the late 1970s and the 1980s.'),
('Ska', 'A music genre that originated in Jamaica in the late 1950s and was the precursor to rocksteady and reggae.'),
('Pop Punk', 'A fusion music genre that combines elements of punk rock with power pop music.'),
('Emo', 'A style of rock music characterized by expressive, often confessional lyrics.'),
('Garage Rock', 'A raw and energetic style of rock and roll that flourished in the mid-1960s.'),
('Surf Rock', 'A subgenre of rock music associated with surf culture, particularly as found in Southern California.'),

-- POP
('Pop', 'A genre of popular music that originated in its modern form during the mid-1950s in the United States and the United Kingdom.'),
('Synth-pop', 'A subgenre of new wave music that first became prominent in the late 1970s and features the synthesizer as the dominant musical instrument.'),
('Electropop', 'A music genre combining elements of electronic and pop genres.'),
('Indie Pop', 'A music genre and subculture that combines guitar pop with DIY ethic in opposition to the style and tone of mainstream pop music.'),
('K-Pop', 'A genre of popular music originating in South Korea.'),
('J-Pop', 'A musical genre that entered the musical mainstream of Japan in the 1990s.'),
('Teen Pop', 'A subgenre of pop music that is oriented towards pre-teens and teenagers.'),
('Dance-Pop', 'A popular music subgenre that originated in the early 1980s. It is generally uptempo music intended for nightclubs with the intention of being danceable but also suitable for contemporary hit radio.'),
('Art Pop', 'A loosely defined style of pop music influenced by pop art''s integration of high and low culture, and which emphasizes the manipulation of signs, style, and appearance over personal expression.'),
('Baroque Pop', 'A fusion genre that combines rock and roll and pop music with classical music, specifically the baroque and classical eras.'),
('Bubblegum Pop', 'A genre of pop music with an upbeat sound contrived and marketed to appeal to pre-teens and teenagers.'),
('Christian Pop', 'A genre of popular music which is lyrically focused on matters concerned with the Christian faith.'),
('Latin Pop', 'A pop music subgenre that is a fusion of US-style music production with Latin American music genres from anywhere in Latin America and Spain.'),
('Country Pop', 'A subgenre of country music and pop music that was developed by members of the country genre out of a desire to reach a larger, mainstream audience.'),
('Disco', 'A genre of dance music and a subculture that emerged in the mid-1970s from the United States'' urban nightlife scene.'),

-- HIP HOP & R&B
('Hip Hop', 'A culture and art movement that was created by African Americans, Latino Americans and Caribbean Americans in the Bronx, New York City.'),
('Rap', 'A musical form of vocal delivery that incorporates "rhyme, rhythmic speech, and street vernacular".'),
('Trap', 'A subgenre of hip hop music that originated in the Southern United States during the early 1990s.'),
('R&B', 'A genre of popular music that originated in African American communities in the 1940s.'),
('Soul', 'A popular music genre that originated in the African American community throughout the United States in the 1950s and early 1960s.'),
('Neo-Soul', 'A genre of popular music. As a term of music marketing, neo-soul describes a style of music that emerged from soul and contemporary R&B.'),
('Funk', 'A music genre that originated in African American communities in the mid-1960s when musicians created a rhythmic, danceable new form of music through a mixture of soul, jazz, and rhythm and blues.'),
('Gospel', 'A genre of Christian music. The creation, performance, significance, and even the definition of gospel music varies according to culture and social context.'),
('Gangsta Rap', 'A subgenre of hip hop music that emerged in the mid-to-late 1980s as a distinct but highly controversial rap subgenre, whose lyrics assert the culture and values of street gangs and street hustlers.'),
('Grime', 'A genre of electronic dance music that emerged in London in the early 2000s.'),
('Drill', 'A subgenre of hip hop music that originated in Chicago in the early 2010s.'),
('Lo-Fi Hip Hop', 'A form of downtempo music that combines elements of hip hop and chill-out music.'),
('Trip Hop', 'A musical genre that originated in the early 1990s in the United Kingdom, especially Bristol.'),
('Old School Hip Hop', 'The earliest commercially recorded hip hop music and the original style of the genre.'),
('Conscious Hip Hop', 'A subgenre of hip-hop that challenges the dominant cultural, political, philosophical, and economic consensus.'),

-- ELECTRONIC
('Electronic', 'Music that employs electronic musical instruments, digital instruments, or circuitry-based music technology in its creation.'),
('House', 'A genre of electronic dance music characterized by a repetitive four-on-the-floor beat and a typical tempo of 120 to 130 beats per minute.'),
('Techno', 'A genre of electronic dance music (EDM) that is characterized by a repetitive four-on-the-floor beat and is generally produced for use in a continuous DJ set.'),
('Trance', 'A genre of electronic music that developed during the 1990s in Germany.'),
('Dubstep', 'A genre of electronic dance music that originated in South London in the early 2000s.'),
('Drum and Bass', 'A genre of electronic music characterized by fast breakbeats (typically 165-185 beats per minute) with heavy bass and sub-bass lines.'),
('Ambient', 'A genre of music that emphasizes tone and atmosphere over traditional musical structure or rhythm.'),
('EDM', 'Electronic Dance Music, a broad range of percussive electronic music genres made largely for nightclubs, raves, and festivals.'),
('Deep House', 'A subgenre of house music that originated in the 1980s, initially fusing elements of Chicago house with 1980s jazz-funk and touches of soul music.'),
('Electro', 'A genre of electronic music and early hip hop directly influenced by the use of the Roland TR-808 drum machines and funk sampling.'),
('IDM', 'Intelligent Dance Music, a style of electronic music suited to home listening rather than dancing.'),
('Synthwave', 'An electronic music microgenre that is based primarily on the music associated with action, science-fiction, and horror film soundtracks of the 1980s.'),
('Vaporwave', 'A microgenre of electronic music and an Internet meme that emerged in the early 2010s.'),
('Hardstyle', 'A Dutch genre of electronic dance music that mixes influences from hard techno and hardcore.'),
('Garage UK', 'A genre of electronic music originating from England in the early 1990s.'),
('Chillout', 'A loosely defined umbrella term for styles of electronic music characterized by their mellow style and mid-tempo beats.'),
('Downtempo', 'A genre of electronic music similar to ambient music but usually with a beat or groove.'),
('Industrial', 'A genre of music that draws on harsh, transgressive or provocative sounds and themes.'),
('Glitch', 'A genre of electronic music that emerged in the late 1990s. It has been described as an "aesthetic of failure".'),
('Breakbeat', 'A broad style of electronic or dance-oriented music which utilizes breaks, often sampled from earlier recordings in funk, jazz, and R&B.'),

-- JAZZ & BLUES
('Jazz', 'A music genre that originated in the African-American communities of New Orleans, Louisiana, United States, in the late 19th and early 20th centuries.'),
('Blues', 'A music genre and musical form which was originated in the Deep South of the United States around the 1860s by African-Americans from roots in African musical traditions.'),
('Swing', 'A form of popular music developed in the United States that dominated in the 1930s and 1940s.'),
('Bebop', 'A style of jazz developed in the early to mid-1940s in the United States, which features songs characterized by a fast tempo, complex chord progressions with rapid chord changes and numerous changes of key.'),
('Cool Jazz', 'A style of modern jazz music that arose in the United States after World War II.'),
('Fusion', 'A music genre that developed in the late 1960s when musicians combined jazz harmony and improvisation with rock music, funk, and rhythm and blues.'),
('Smooth Jazz', 'A commercially oriented genre of jazz that became dominant in the 1980s and early 1990s.'),
('Acid Jazz', 'A musical genre that combines elements of jazz, soul, funk, and disco.'),
('Free Jazz', 'An approach to jazz music that was first developed in the 1950s and 1960s as musicians attempted to alter, extend, or break down jazz convention.'),
('Ragtime', 'A musical style that enjoyed its peak popularity between 1895 and 1919. Its cardinal trait is its syncopated or "ragged" rhythm.'),
('Dixieland', 'A style of jazz music which developed in New Orleans at the start of the 20th century.'),
('Delta Blues', 'One of the earliest styles of blues music. It originated in the Mississippi Delta.'),
('Chicago Blues', 'A form of blues music that developed in Chicago, Illinois. It is based on earlier blues idioms, such as Delta blues, but performed in an urban style.'),
('Rhythm and Blues', 'A genre of popular music that originated in African American communities in the 1940s.'),
('Soul Jazz', 'A development of jazz incorporating strong influences from blues, soul, gospel and rhythm and blues.'),

-- CLASSICAL & ORCHESTRAL
('Classical', 'Art music produced or rooted in the traditions of Western culture, including both liturgical (religious) and secular music.'),
('Baroque', 'A period of Western art music composed from approximately 1600 to 1750.'),
('Romantic', 'A stylistic movement in Western orchestral music associated with the period of the 19th century commonly referred to as the Romantic era.'),
('Opera', 'A form of theatre in which music has a leading role and the parts are taken by singers, but is distinct from musical theatre.'),
('Symphony', 'An extended musical composition in Western classical music, most often written by composers for orchestra.'),
('Chamber Music', 'A form of classical music that is composed for a small group of instruments—traditionally a group that could fit in a palace chamber or a large room.'),
('Gregorian Chant', 'The central tradition of Western plainchant, a form of monophonic, unaccompanied sacred song in Latin of the Roman Catholic Church.'),
('Minimalism', 'A form of art music or other compositional practice that employs limited or minimal musical materials.'),
('Neoclassical', 'A twentieth-century trend, particularly current in the interwar period, in which composers sought to return to aesthetic precepts associated with the broadly defined concept of "classicism".'),
('Avant-Garde', 'Music that is considered to be at the forefront of experimentation or innovation in its field.'),

-- COUNTRY & FOLK
('Country', 'A genre of popular music that originated with blues, old-time music, and various types of American folk music.'),
('Bluegrass', 'A genre of American roots music that developed in the 1940s in the United States Appalachian region.'),
('Folk', 'Music that originates in traditional popular culture or that is written in such a style.'),
('Americana', 'Contemporary music that incorporates elements of various American roots music styles, including country, roots-rock, folk, bluegrass, R&B and blues.'),
('Honky Tonk', 'A type of bar that provides country music for the entertainment of its patrons.'),
('Outlaw Country', 'A subgenre of country music, most popular during the late 1960s and the 1970s.'),
('Rockabilly', 'One of the earliest styles of rock and roll music. It dates back to the early 1950s in the United States, especially the South.'),
('Western Swing', 'A subgenre of American country music that originated in the late 1920s in the West and South among the region''s Western string bands.'),
('Contemporary Folk', 'A wide variety of genres that emerged in the mid-20th century and afterwards which were associated with traditional folk music.'),
('Celtic', 'A broad grouping of music genres that evolved out of the folk musical traditions of the Celtic people of Western Europe.'),

-- LATIN & CARIBBEAN
('Salsa', 'A popular dance music genre that initially arose in New York City during the 1960s.'),
('Bachata', 'A genre of Latin American music that originated in the Dominican Republic in the first half of the 20th century.'),
('Merengue', 'A style of Dominican music and dance.'),
('Reggaeton', 'A music style that originated in Puerto Rico during the mid-1990s. It has evolved from dancehall and influenced by American hip hop, Latin American, and Caribbean music.'),
('Cumbia', 'A folkloric rhythm and dance from Colombia.'),
('Tango', 'A partner dance and social dance that originated in the 1880s along the River Plate, the natural border between Argentina and Uruguay.'),
('Bossa Nova', 'A style of Brazilian music, which developed and was popularized in the 1950s and 1960s and is today one of the best-known Brazilian music genres abroad.'),
('Samba', 'A Brazilian music genre and dance style, with its roots in Africa via the West African slave trade and African religious traditions.'),
('Mariachi', 'A style of music and musical group performance that dates back to at least the 18th century, evolving over time in the countryside of various regions of western Mexico.'),
('Flamenco', 'An art form based on the various folkloric music traditions of southern Spain, developed within the gitano subculture of the region of Andalusia.'),
('Reggae', 'A music genre that originated in Jamaica in the late 1960s.'),
('Dancehall', 'A genre of Jamaican popular music that originated in the late 1970s.'),
('Soca', 'A genre of music that originated within a marginalized subculture in Trinidad and Tobago in the early 1970s, and developed into a range of styles by the 1980s and later.'),
('Calypso', 'A style of Afro-Caribbean music that originated in Trinidad and Tobago during the early to mid-19th century.'),
('Afrobeat', 'A music genre that involves the combination of elements of West African musical styles such as fuji music and highlife with American jazz and later soul and funk influences.'),

-- WORLD & OTHERS
('Klezmer', 'A musical tradition of the Ashkenazi Jews of Eastern Europe.'),
('Polka', 'A Central European dance and also a genre of dance music familiar throughout Europe and the Americas.'),
('Fado', 'A music genre that can be traced to the 1820s in Lisbon, Portugal, but probably has much earlier origins.'),
('Bollywood', 'Filmi music, the music of the Indian film industry.'),
('J-Rock', 'Japanese rock music.'),
('Afropop', 'Popular music from Africa.'),
('World Music', 'A musical category encompassing many different styles of music from around the globe, including traditional music, non-Western folk music, and music where more than one cultural tradition intermingle.'),
('New Age', 'A genre of music intended to create artistic inspiration, relaxation, and optimism.'),
('Soundtrack', 'Recorded music accompanying and synchronized to the images of a motion picture, book, television program, or video game.'),
('Musical Theatre', 'A form of theatrical performance that combines songs, spoken dialogue, acting and dance.'),
('Acapella', 'Group or solo singing without instrumental accompaniment.'),
('Choral', 'Music written specifically for such an ensemble to perform.'),
('Lo-Fi', 'Low-fidelity music is a musical quality in which elements usually regarded as imperfections of a recording or performance are audible.'),
('Noise', 'A category of music that is characterised by the expressive use of noise within a musical context.'),
('Experimental', 'A general label for any music that pushes existing boundaries and genre definitions.'),
('Instrumental', 'A musical composition or recording without lyrics, or singing, although it might include some inarticulate vocal input.'),
('Easy Listening', 'A popular music genre and radio format that was most popular during the 1950s to 1970s.'),
('Lounge', 'A type of easy listening music popular in the 1950s and 1960s.'),
('Cabaret', 'A form of theatrical entertainment featuring music, song, dance, recitation, or drama.'),
('Spoken Word', 'An oral art that focuses on the aesthetics of word play such as intonation and voice inflection.'),
('Children''s Music', 'Music performed for children, which is often designed to provide an entertaining means of teaching about subjects.'),
('Comedy', 'Music that is comic or humorous in nature.'),
('Holiday', 'Music associated with a holiday, most commonly Christmas.'),
('Parody', 'A creative work designed to imitate, comment on, and/or make fun of its subject by means of satiric or ironic imitation.'),
('Mashup', 'A creative work, usually in a form of a song, created by blending two or more pre-recorded songs, typically by superimposing the vocal track of one song seamlessly over the instrumental track of another.'),
('Remix', 'A piece of media which has been altered from its original state by adding, removing, and/or changing pieces of the item.'),
('Cover', 'A new performance or recording by someone other than the original artist or composer of a previously recorded, commercially released song.'),
('Live', 'Music performed in real time.'),
('Acoustic', 'Music that solely or primarily uses instruments that produce sound through acoustic means, as opposed to electric or electronic means.'),
('Unplugged', 'Music performed with acoustic instruments instead of electric ones.'),
('Video Game Music', 'The soundtrack and background music of video games.'),
('Anime', 'Music used in anime productions, including opening and ending themes and background music.'),
('Vocaloid', 'Music created using the Vocaloid singing synthesizer software.'),
('Nightcore', 'A style of remix that speeds up the pitch and tempo of a source track by 20–30%.'),
('Hardcore', 'A subgenre of punk rock that originated in the late 1970s. It is generally faster, harder, and more aggressive than other forms of punk rock.');
